---
---

<link rel="stylesheet" href="styles.css" type="text/css">

**PhD defense** Tuesday June 29 at 4pm (in France) online, [dissertation](files/these_archivage_3300796.pdf), [slides]()

**News** Appel à contribution, pour le Congrès des Jeunes Chercheurs en Mathématiques Appliquées du  27 au 29 octobre à l’École Polytechnique. Plus d'informations [ici](https://indico.math.cnrs.fr/event/6488/abstracts/). Pour soumettre, c'est [ici](https://indico.math.cnrs.fr/event/6488/abstracts/) jusqu'au 25 mai 2021.

I am a third year PhD student in Mathematics supervised by Doctors Julie Josse and Claire Boyer at Ecole Polytechnique (CMAP) and University Pierre and Marie Curie (LPSM).

My research is focused on the estimation of high dimensional incomplete matrices, which contain missing data generated by the specific MAR and MNAR mechanisms. The key issue is to perform predictive models for public health applications with the APHP Traumabase Group.

Here you can find [my detailed resume](files/resume_Sportisse.pdf).