---
---

<link rel="stylesheet" href="styles.css" type="text/css">

**Papers**

* [Robust Lasso-Zero for sparse corruption and model selection with missing covariates](https://arxiv.org/abs/2005.05628) (2020, submitted), Pascaline Descloux, Claire Boyer, Julie Josse, Aude Sportisse, Sylvain Sardy

* [Debiasing Stochastic Gradient Descent to handle missing values](https://arxiv.org/abs/2002.09338) (NeurIPS 2020), Aude Sportisse, Claire Boyer, Aymeric Dieuleveut, Julie Josse

* [Estimation and Imputation in Probabilistic Principal Component 
Analysis with Missing Not At Random Data](https://arxiv.org/abs/1906.02493) (NeurIPS 2020), Aude Sportisse, Claire Boyer, Julie Josse

* [Imputation and low-rank estimation with Missing Not At Random data](https://arxiv.org/abs/1812.11409) (2018, Statistics & Computing, Springer), Aude Sportisse, Claire Boyer, Julie Josse

**Talks** 

* Debiasing Stochastic Gradient Descent to handle missing values, October 5. 2020, MIA Seminar, AgroParisTech

* [Robust Lasso-Zero for sparse corruption and model selection with missing covariates](files/Lass0_Sportisse.pdf), July 3. 2020, [One World : statistical learning seminars](https://statistical-learning-seminars.github.io)


* [Estimation and Imputation in Probabilistic Principal Component 
Analysis with Missing Not At Random Data](files/PPCA_MNAR_2020.pdf), June 18. 2020, Simpas Group Meeting, Ecole Polytechnique


* [Estimation with informative missing data in the low-rank model with random effects](files/JDS2019_Sportisse.pdf), June 7. 2019, Journées de Statistique 2019, Nancy

* [Imputation and low-rank estimation with Missing Not At Random data](files/Dagstat2019_Sportisse.pdf), March 21. 2019, DAGStat Conference, LMU Münich 

* Low rank estimation with MNAR data, September 5. 2018, Group Meeting, University Pierre and Marie Curie

**Posters** 

* [Estimation with informative missing data in the low-rank model with random effects](files/poster_DS3_2019.pdf), June 24.-28. 2019, Data Science Summer School, Ecole Polytechnique 

* Low rank estimation with MNAR data, June 25. 2018, Data Science Summer School, Ecole Polytechnique
